package ks52team01.student.score.dto;

import lombok.Data;

@Data
public class SecondLanguageAndChineseCharactersScoreAvg {
	
	private Double secondLanguageAndChineseCharactersOriginNationAvg;
	private Double secondLanguageAndChineseCharactersOriginProvinceAvg;
	private Double secondLanguageAndChineseCharactersOriginMunicipalityAvg;
	
	private Double secondLanguageAndChineseCharactersStandardNationAvg;
	private Double secondLanguageAndChineseCharactersStandardProvinceAvg;
	private Double secondLanguageAndChineseCharactersStandardMunicipalityAvg;
	
	private Double secondLanguageAndChineseCharactersPercentNationAvg;
	private Double secondLanguageAndChineseCharactersPercentProvinceAvg;
	private Double secondLanguageAndChineseCharactersPercentMunicipalityAvg;
	
	private Double secondLanguageAndChineseCharactersGradeNationAvg;
	private Double secondLanguageAndChineseCharactersGradeProvinceAvg;
	private Double secondLanguageAndChineseCharactersGradeMunicipalityAvg;
	
	private Double secondLanguageAndChineseCharactersRankNationAvg;
	private Double secondLanguageAndChineseCharactersRankProvinceAvg;
	private Double secondLanguageAndChineseCharactersRankMunicipalityAvg;
	
}
